[package]
name = "jnickg_rust_explorations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "jnickg_imaging"
path = "src/lib.rs"

[dependencies]
num = "0.4.1"
rocket = "0.5.0"
